#!/usr/bin/env python3
"""Generate the vec_swizzle_decl.hpp macro file.

The output header only contains one preprocessor macro per (source size,
result size) pair.  Each macro expands to the full set of swizzle member
declarations for that pair; the actual declaration is emitted through the
context macros ``EIRIN_TVEC_SWIZZLE_IMPL_2/3/4``, which are defined by
``vec_swizzle.hpp`` when the macro is expanded.

The generated file is written to ``tools/vec_swizzle_decl.hpp``.  Move it
into the include tree with ``tools/install_swizzle_decl.py``.
"""

from __future__ import annotations

import itertools
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT = SCRIPT_DIR / "vec_swizzle_decl.hpp"

COMPONENTS = {
    2: "xy",
    3: "xyz",
    4: "xyzw",
}

# Result sizes are independent from the source size: a vec2 can already
# produce swizzles of length 2, 3 and 4 (e.g. ``v2.xxyy()``).
RESULT_SIZES = (2, 3, 4)


def letters_for(source_size: int) -> str:
    """Return the letter names of the components of a source vector."""
    return COMPONENTS[source_size]


def build_family_macro(source_size: int, result_size: int) -> str:
    """Build one ``EIRIN_TVEC_SWIZZLE{S}_{R}_MEMBERS_DECL`` macro."""
    letters = letters_for(source_size)
    params = ", ".join(f"E{i}" for i in range(source_size))
    header = f"#define EIRIN_TVEC_SWIZZLE{source_size}_{result_size}_MEMBERS_DECL(T, {params})"

    lines = [header + " \\"]
    for name_letters in itertools.product(letters, repeat=result_size):
        # Token-paste the macro parameter names: "xy" -> E0##E1.
        name = "##".join(f"E{letters.index(ch)}" for ch in name_letters)
        indices = ", ".join(str(letters.index(ch)) for ch in name_letters)
        invocation = f"    EIRIN_TVEC_SWIZZLE_IMPL_{result_size}({source_size}, {name}, {indices})"
        lines.append(invocation + " \\")
    lines[-1] = lines[-1].rstrip(" \\")
    return "\n".join(lines)


def main() -> None:
    """Write the generated macro header to tools/."""
    chunks = [
        "// Auto-generated swizzle macros. DO NOT edit manually.",
        "// Generated by gen_swizzle_macros.py",
        ""
    ]
    for source_size in COMPONENTS:
        for result_size in RESULT_SIZES:
            chunks.append(build_family_macro(source_size, result_size))
            chunks.append("")

    OUTPUT.write_text("\n".join(chunks), encoding="utf-8")
    print(f"generated {OUTPUT}")


if __name__ == "__main__":
    main()
